// <auto-generated />
using System;
using GoalkeeperSchoolDataAcess.DataAcess.Controlers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalkeeperSchoolDataAcess.Migrations
{
    [DbContext(typeof(GoalkeeperSchoolDBControler))]
    [Migration("20230131145352_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.Account", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.FullName", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paternity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FullNames");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.GoalkeeperProfile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FullNameID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("FullNameID");

                    b.ToTable("GoalkeeperProfiles");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.GoalkeeperProfile", b =>
                {
                    b.HasOne("GoalkeeperSchoolDataAcess.Models.Account", null)
                        .WithMany("GoalkeeperProfiles")
                        .HasForeignKey("AccountID");

                    b.HasOne("GoalkeeperSchoolDataAcess.Models.FullName", "FullName")
                        .WithMany()
                        .HasForeignKey("FullNameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FullName");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.Account", b =>
                {
                    b.Navigation("GoalkeeperProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
