// <auto-generated />
using System;
using GoalkeeperSchoolDataAcess.DataAcess.Controlers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalkeeperSchoolDataAcess.Migrations
{
    [DbContext(typeof(GoalkeeperSchoolDBControler))]
    [Migration("20230131211959_SchemaComponentsAdded")]
    partial class SchemaComponentsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.DB.DBAccount", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.DB.DBFullName", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Paternity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("FullNames");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.DB.DBGoalkeeperProfile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DBAccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DbFullNameID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("DBAccountID");

                    b.HasIndex("DbFullNameID");

                    b.ToTable("GoalkeeperProfiles");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.DB.DBGoalkeeperProfile", b =>
                {
                    b.HasOne("GoalkeeperSchoolDataAcess.Models.DB.DBAccount", null)
                        .WithMany("GoalkeeperProfiles")
                        .HasForeignKey("DBAccountID");

                    b.HasOne("GoalkeeperSchoolDataAcess.Models.DB.DBFullName", "DbFullName")
                        .WithMany()
                        .HasForeignKey("DbFullNameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DbFullName");
                });

            modelBuilder.Entity("GoalkeeperSchoolDataAcess.Models.DB.DBAccount", b =>
                {
                    b.Navigation("GoalkeeperProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
